name: Manual deployment
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ansible
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
